apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/todos/1-project-ns.yaml
  - manifests/todos/configmap.yaml
  - manifests/todos/backend-deployment.yaml
  - manifests/todos/persistentvolumeclaim.yaml
  - manifests/todos/frontend-deployment.yaml
  - manifests/todos/backend-service.yaml
  - manifests/todos/frontend-service.yaml
  - manifests/todos/pg-configmap.yaml
  - manifests/todos/postgres-sset.yaml
  - manifests/todos/postgres-service.yaml
  - manifests/todos/pg-dump-cronjob.yaml
  - manifests/todos/project-sa.yaml
  - manifests/todos/cron-job.yaml
  - manifests/todos/gateway.yaml
  - manifests/todos/route.yaml
  - manifests/todos/hpa-frontend.yaml
  - manifests/todos/hpa-backend.yaml
  - manifests/todos/pdb-frontend.yaml
  - manifests/todos/pdb-backend.yaml
images:
  - name: backend-image
    newName: europe-north1-docker.pkg.dev/dwk-gke-485610/my-repo/todo-backend:4.5
  - name: frontend-image
    newName: europe-north1-docker.pkg.dev/dwk-gke-485610/my-repo/todo-frontend:4.5