apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/logging/ingress.yaml
  - manifests/logging/wr-logs-deployment.yaml
  - manifests/logging/wr-logs-service.yaml
  - manifests/logging/argo-cd.yaml
images:
  - name: logoutput-image
    newName: kawpii/logoutput
    newTag: "47"