apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1-project-ns.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - persistentvolumeclaim.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml
  - pg-configmap.yaml
  - postgres-sset.yaml
  - postgres-service.yaml
  - pg-dump-cronjob.yaml
  - project-sa.yaml
  - cron-job.yaml
  - gateway.yaml
  - route.yaml
  - hpa-frontend.yaml
  - hpa-backend.yaml
  - pdb-frontend.yaml
  - pdb-backend.yaml
  - argo-cd.yaml
