apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  namespace: project
  annotations:
    iam.gke.io/gcp-service-account: postgres-backup-gsa@dwk-gke-485610.iam.gserviceaccount.com