apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kawpii/k8s-mooc.git
    targetRevision: main
    path: manifests/todos

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true