name: Build and publish Todo application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |-
          docker build --tag "kawpii/todo-frontend-staging:$GITHUB_SHA" ./todo-frontend
          docker push "kawpii/todo-broadcaster-staging:$GITHUB_SHA"
          docker build --tag "kawpii/todo-backend-staging:$GITHUB_SHA" ./todo-backend
          docker push "kawpii/todo-broadcaster-staging:$GITHUB_SHA"
          docker build --tag "kawpii/todo-broadcaster-staging:$GITHUB_SHA" ./todo-broadcaster
          docker push "kawpii/todo-broadcaster-staging:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd manifests/todos/staging && kustomize edit set image PROJECT/IMAGE=backend-image:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE=frontend-image:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE=broadcaster-image:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}